name: coauthor-action
description: Compile a list of coauthors involved in a pull request and post the "Coauthor-by" string as a comment.
author: Kevin Zuniga Cuellar

branding:
  icon: 'heart'
  color: 'purple'

inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  trigger-phrase:
    description: 'The phrase that triggers the action.'
    default: '!coauthor'

runs:
  using: node20
  main: dist/index.js